name: "FibBot"
description: "My Rust application(bot(fibbot))"
author: "Nyengka Prosper"

inputs:
  enable_fib:
    description: "Enable Fibonacci calculation (true/false)"
    required: false
    default: "true"
  max_threshold:
    description: "Max threshold for Fibonacci calculation"
    required: false
    default: "1000"
  github_token:
    description: "GitHub token to interact with GitHub API"
    required: true
  pr_number:
    description: "The number of the pull request"
    required: true
    default: "1"

runs:
  using: "composite"
  steps:
    - name: Build FibBot
      run: cargo build --release
      shell: bash

    - name: Run FibBot
      run: |
        export PR_NUMBER="${{ inputs.pr_number }}"
        export ENABLE_FIB="${{ inputs.enable_fib }}"
        export GITHUB_TOKEN="${{ inputs.github_token }}"
        ./target/release/fibbot "${{ inputs.enable_fib }}" "${{ inputs.max_threshold }}" "${{ inputs.pr_number }}" "${{ inputs.github_token }}" 
      shell: bash
branding:
  icon: "activity"
  color: "blue"
