name: Fibbot
author: Nyengka Prosper
description: My Rust application(bot(fibbot))
branding:  
  icon: align-left
  color: blue
inputs:
  enable_fib:
    description: Arguments passed to `fibbot` to enable fibonacci calculation
    required: false
    default: "true"
  max_threshold:
    description: Other argument to set maximum number allowed for fibonacci calculation
    required: false
    default: "1000"
runs:
  using: "docker"
  image: "Dockerfile"

