name: Fibbot
author: Nyengka Prosper
description: My Rust application(bot(fibbot))
branding:  
  icon: align-left
  color: blue
input:
  enable_fib:
    description: Arguments passed to `fibbot` to enable fibonacci calculation
    required: false
    default: "true"
  max_threshold:
    description: Other argument to set maximum number allowed for fibonacci calculation
    required: true
    default: "1000"
#outputs:
#  results:
#    description: The results from calling `fibbot`
runs:
  using: "docker"
  image: "Dockerfile"
 # args:
 # - ${{ inputs.args }}
#branding:
#  icon: "hash"
#  color: "green"
