[package]
name = "fibbot"
version = "0.1.0"
edition = "2021"

[dependencies]
octocrab = "0.32"
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
regex = "1"
num-bigint="0.4.3"
num-traits="0.2.14"


