on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
      - FibBot
permissions:
  pull-requests: write
  contents: read

jobs:
  run-fibbot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Run FibBot
        uses: Prosper-ador/FibBot@main
        with:
          pr_number: ${{ github.event.pull_request.number || 1 }}
          enable_fib: "true"
          max_threshold: "1000"
          github_token: ${{ secrets.GITHUB_TOKEN }}  
