name: "Run FibBot"

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
      - Fibbot

permissions:
  pull-requests: write
  contents: read

jobs:
  run-fibbot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set PR number in the environment
        run: echo "GITHUB_PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: Run FibBot
        uses: Prosper-ador/FibBot@main
        with:
          enable_fib: "true"
          max_threshold: "1000"
          github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_PR_NUMBER: ${{ env.GITHUB_PR_NUMBER }}  # Pass the env variable to the actio
          
      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          script: |
            const comment = require("./comment.js");
            await comment.commentOnPR(context);

            