name: "Run FibBot"

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
    inputs:
      pr_number:
        description: "PR Number to Process"
        required: false
        default: "2"
  push:
    branches:
      - main
      - Fibbot

permissions:
  pull-requests: write
  contents: read

jobs:
  run-fibbot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run FibBot
        uses: Prosper-ador/FibBot@main
        with:
          enable_fib: "true"
          max_threshold: "1000"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_number: ${{ github.event.pull_request.number }}
          
      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          script: |
            const comment = require("./comment.js");
            await comment.commentOnPR(context);