name: "Run FibBot"

on:
  pull_request:
    types: [opened, synchronize, closed]
 
permissions:
      pull-requests: write
      contents: write
      issues: write


jobs:
  run-fibbot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
  branches:
        - main
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set PR number in the environment
        run: echo "GITHUB_PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: Run FibBot
        uses: Prosper-ador/FibBot@main
        with:
          enable_fib: "true"
          max_threshold: "1000"
          github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_PR_NUMBER: ${{ env.GITHUB_PR_NUMBER }}  # Pass the env variable to the action

            