name: "FibBot CI"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  pull-requests: write
  contents: read

jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run FibBot Action
        uses: /Prosper-ador/FibBot/@main
