#trigger-action-file
name: Fibbot
on: [push, pull_request]

jobs:
  check:  # Any action can contain multiple jobs
    runs-on: ubuntu-latest  # OS on which the job runs
    steps:  # Each job consists in a series of steps
    - name: Checkout repository # Clone git repository
      uses: actions/checkout@v4

    - name: Check that code can compile
      run: cargo check  # Run the `cargo check` command
    
    - name: Run Fibbot
      uses: ./
